import { useState, useEffect } from 'react';
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Novi Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {mobileDisplay ? <h1>MOBILE</h1> : <h1>DESKTOP</h1>} */}
      <div>Hello world</div>
    </div>
  );
};

export default Home;
